// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlmr-Sy1_AkAAw92ATeOhil2tli5J9hIc',
    appId: '1:251872576271:web:6523269988fe0c57f5f47a',
    messagingSenderId: '251872576271',
    projectId: 'chatapp-cef95',
    authDomain: 'chatapp-cef95.firebaseapp.com',
    storageBucket: 'chatapp-cef95.appspot.com',
    measurementId: 'G-PJVGKSYM1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnAzNmC0l5H9BQ8kMTBwgxT31QffPgpXc',
    appId: '1:251872576271:android:479dd755d5110dccf5f47a',
    messagingSenderId: '251872576271',
    projectId: 'chatapp-cef95',
    storageBucket: 'chatapp-cef95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVCBSCSHPXRlwj-dVEoRmjsA4Kdrjr_is',
    appId: '1:251872576271:ios:0a2a0ccdda3a3755f5f47a',
    messagingSenderId: '251872576271',
    projectId: 'chatapp-cef95',
    storageBucket: 'chatapp-cef95.appspot.com',
    iosBundleId: 'com.example.hashtag',
  );
}
